#!/usr/bin/env bash
#  parses through /etc/passwd

IFS=":"

while read -r username password _ gid _ homedir shell; do
	echo "The user $username is a part of the $gid gang, lives in $homedir and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd
