#!/usr/bin/env bash
#  This script prints out "Best School" 10 times using while loop
#+ and on the 9th iteration of printing "Best School" outputs "Hi"
i=0
len=10
while [ "$i" -lt "$len" ]
do
        echo "Best School"
	(( i = i + 1 ))
	if [ "$i" -eq 9 ]; then
		echo "Hi"
	fi
done
