#!/usr/bin/env bash
#  This script displays numbers from 1-20 and
#+ includes annotations on the 4th, 9th and 17th iterations

i=1
len=21
while [ "$i" -lt "$len" ]
do
	case $i in
		4)
		echo "$i"
		echo "bad luck from China"
		;;
		9)
		echo "$i"
		echo "bad luck from Japan"
		;;
		17)
		echo "$i"
		echo "bad luck from Italy"
		;;
		*)
		echo "$i"
		;;
	esac
	(( i = i + 1 ))
done
